import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Form from '../features/components/Form'
import Form2 from '../features/components/Form2'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Form />
        <br />
        <br />
        <Form2 />
      </main>
    </div>
  )
}

export default Home
